### ISSUE TITLE
lista unica 

### ISSUE THREAD

**Issue by CaioDeneditoDrumond** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#1]
Olá boa tarde .
Pedro tem como  adicionar uma funçao no source   lista unica e tbm fuçao escolha  por emuladores, estilo  a funçao que vc deixou gratis/pago.
Ai ficaria assim      Lista ( Unica/Emuladores).
E tambem queria saber se tem como colocas os emuladores separados ao inves de esta no retroarch e como muda essa funçoes no source, rc e amp.

Desde já grato .

**Comment by pedrowarlock** [comment]
O sistema é modificado ao gosto do público.  Não posso fazer uma edição personalizado ao seu gosto.

Para instalar o retroarch, apenas coloque na pasta "Retroarch32" para o sistema retroarch 32 bits e na pasta "Retroarch64" para o emulador retroarch 64 bits. 

Ps: Não esqueça de baixar os cores do retroarch para rodar o emulador que você queira.


Ps: O sistema está na pasta "src". Boa sorte nos estudos.

**Comment by CaioDeneditoDrumond** [comment]
Eu queria deixa os emuladores sem ser pelo retroarch  mas sim deixa por emuladores  individual na pasta emuladores, ajudaria colocar esssa funçao se possivel, pq uma ideia legal e diferente num souce e para aparece na mutijogos a funçao  Lista ( Unica/Emuladores) igual  como vc fez nessa funçao vc deixou gratis/pago. Seria uma coisa diferente e nova na multijogos

**Comment by pedrowarlock** [comment]
Sim, você pode. Só você fazer o seguinte.

Abra o arquivo "advmenu.rc"

Abaixo você vê um exemplo de como está configurado para usar o retroarch. O que você deve fazer...Mude o caminho do executavel do retroarch para o executavel do seu emulado:
Exemplo:
 Mude de:
emulator "Playstation1" generic ".\Emuladores\retroarch32\retroarch.exe "%p"  

  Para:
emulator "Playstation1" generic ".\Emuladores\epsx\epsx.exe "%p"  


em seguida, vá até a pasta "ini" e procure por "Playstation1.ini" abra ele com o bloco de notas. Procure por "Retroarch = 1"  e mude o valor para 0

RETROARCH    = 0

**Comment by CaioDeneditoDrumond** [comment]
vc pensou nessa funçao de  lista unica /emuladores  seria uma novidade

**Comment by CaioDeneditoDrumond** [comment]
> Sim, você pode. Só você fazer o seguinte.
> 
> Abra o arquivo "advmenu.rc"
> 
> Abaixo você vê um exemplo de como está configurado para usar o retroarch. O que você deve fazer...Mude o caminho do executavel do retroarch para o executavel do seu emulado:
> Exemplo:
> Mude de:
> emulator "Playstation1" generic ".\Emuladores\retroarch32\retroarch.exe "%p"
> 
> Para:
> emulator "Playstation1" generic ".\Emuladores\epsx\epsx.exe "%p"
> 
> em seguida, vá até a pasta "ini" e procure por "Playstation1.ini" abra ele com o bloco de notas. Procure por "Retroarch = 1" e mude o valor para 0
> 
> RETROARCH = 0

    Mas fazendo isso  os emuladores que add ele vão ficar por tempo e ficha tbm,pq eu fi num video de uma multijgos sua os emuladores esta dentro da pasta (emuladores)

**Comment by pedrowarlock** [comment]
Para transformar o emulador em "ficha". Abra o sistema, selecione o emulador que você adicionou, aperte F8, selecione "Tipo de emulador FICHA/TEMPO" selecione o moto ficha ou tempo que você queira.

**Comment by CaioDeneditoDrumond** [comment]
vc vai criar a função no souce q falei sobre a parte de lista para  pessoa querer os emuladores  em lista unica ou como esta por escolha de emuladores

**Comment by CaioDeneditoDrumond** [comment]
estou com um problema nao esta aparecendo bolinhaaqui sera que vc pode me ajudar.



[menu.zip](https://github.com/pedrowarlock/advmenuPlus-PedroWarlock-comercial-system/files/3998799/menu.zip)
