### ISSUE TITLE
TAITO X2

### ISSUE THREAD

**Issue by esiocosta** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#12]
pedro, como adicionar jogos taito ?
eu criei um .lnk  no jogos/taito.
o jogo inicia normal, transfere a ficha mas não fecha o jogo

no games.ini eu acrescentei o jogo também.

o executável do jogo deve ser especifico ? tipo game.exe

**Comment by esiocosta** [comment]
resolvi

no GameLauncher.au3

na linha 746 acrescentei uma função extra para chamar um bat para da taskkill no game.
como jogos taito alguns jogos não pode mudar o nome do exe eu criei um bat para essa tarefa.


Func _ProcessCloseEX()
	ProcessClose($READ_EXE)
	ProcessClose($READ_LOADER)
        **ShellExecute("fecha.bat", "open",".\")**
EndFunc

**Comment by pedrowarlock** [comment]
não use Bat. O gamelauncher vai perder o controle de execução.

**Comment by esiocosta** [comment]
o bat é apenas para fechar os jogos taito
