### ISSUE TITLE
REMOVER EMULADOR

### ISSUE THREAD

**Issue by esiocosta** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#14]
pedro, o remover emulador não esta funcionando.
vc remove e reinicia o advmenu mas o emulador não fica oculto

`no mconfig.cc 

//Verifica se o emulador está removido ou adicionado ao sistema
		int Ret=0;
		char buffer1[100];
		Ret = GetPrivateProfileStringA("REMOVER_EMULADOR",a0.c_str(),"0", buffer1, 100, ".\\advmenu.ini"); 
		if (Ret){ //warlock
			if (atoi(buffer1) <= 0) {
				emu.insert(emu.end(), e);
			} else{
				
conf_remove(config_context, "", "emulator_include"); //warlock Move o menu para o priemiro emulador

 `

o advmenu esta verificando no advmenu.ini e não na pasta ini

**Comment by esiocosta** [comment]
no mconfig.cc 

//Verifica se o emulador está removido ou adicionado ao sistema
		int Ret=0;
		char buffer1[100];
		Ret = GetPrivateProfileStringA("REMOVER_EMULADOR",a0.c_str(),"0", buffer1, 100, ".\\advmenu.ini"); 
		if (Ret){ //warlock
			if (atoi(buffer1) <= 0) {
				emu.insert(emu.end(), e);
			} else{
				
				conf_remove(config_context, "", "emulator_include"); //warlock Move o menu para o priemiro emulador

o advmenu esta verificando no advmenu.ini e não na pasta ini

**Comment by pedrowarlock** [comment]
está funcionando normalmente aqui.

**Comment by fabriciocr2** [comment]
Qual partição você usa seu mame Pedro? Aqui também não está funcionando essa função de remover...

**Comment by fabriciocr2** [comment]
esiocosta conseguiu resolver? Estou com o mesmo problema...

**Comment by pedrowarlock** [comment]
Problema resolvido.
