### ISSUE TITLE
nao estou conseguindo jogar os jogos com joystic 

### ISSUE THREAD

**Issue by jefXD** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#16]
tarde Pedro!! eu tenho um controle estilo Playstation genérico quando entro no emulador nintendinho o controle nao funciona nao da start nos jogos os personagens nao se meche não é possível jogar. entrei la na pasta do advmenu no executável >>> ConfigurarControle.exe e configurei ta respondendo os botoes mas quando entro no jogos abre ok mais o controle nao funciona!! só funciona pelo teclado do pc quando entro no jogo aparece uma pequena mensagem no canto da tela USB JOYSTIC NAO CONFIGURADO como faço para os jogos funcionar no controle???
o arquivo ini esta assim 
[configuracao]
nome= Nintendinho
COMANDO1   ="-f"
COMANDO2   =
OCULTAR=0
CONTADOR=0
JOYTOKEY=1

[Retroarch]
RETROARCH    = 1
SINGLE_CORE  = mesen_libretro.dll
SINGLE_CONF  = .\config\nintendinho.cfg

**Comment by pedrowarlock** [comment]
você precisa apertar F1 para configurar o controle do seu emulador, isso no caso do retroarch

**Comment by jefXD** [comment]
obrigado pela informação!!
