### ISSUE TITLE
erro ao troca o  mame

### ISSUE THREAD

**Issue by CaioDeneditoDrumond** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#18]
Ola  vc pode explicar  como fazer para nao perde a fução credito manual na multijogos  se colocar um outro mame. pq quando coloca outro mame os creitos as vezes vai se deixa em modo automatico,e tira aquela funçao    (CREDITOS NO MENU) que a opção colocar credito manualmente.

**Comment by pedrowarlock** [comment]
as mudanças são baseadas no pessoal da comunidade. Não posso fazer alterações específicas para cada usuário

**Comment by CaioDeneditoDrumond** [comment]
acho q tds tem a vontade de colocar outro mame um mas  avançado
