### ISSUE TITLE
pergunta sobre o mame do advmenu??

### ISSUE THREAD

**Issue by jefXD** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#19]
tarde Pedro!!quando entro nos jogos do mame aparece um numero de telefone. tem como você enviar esse mesmo  mame dessa sua multi jogos advmenu mas sem numero de telefone?? ou ensinar como tirar numero?? eu queria tira o numero por questão estética do jogo fiz varias tentativas trocando o mame mas que acontece ou nao funciona e quando funciona as mesmas funções do outro mame não vão funcionar em outro mame tipo funções como auto envio de fichas e desaparece as mensagens de credito funções assim.

**Comment by pedrowarlock** [comment]
o número do telefone não vai sair do mame.
