### ISSUE TITLE
Controles

### ISSUE THREAD

**Issue by mpanjo** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#2]
Bom amigo, muito show seu sistema, so nao entendi como configuro o controle para usar os direcionais no menu system, poderia me dar uma luz obrigado

**Comment by pedrowarlock** [comment]
(FICHA): Você aperta o botão que irá adicionar ficha ao sistema, geralmente ligado ao moedeiro do arcade

(DIPSWITCH) é um botão interno da maquina de fliperama, é aquele botãozinho escondido que abre o painel de configurações, que você edita algumas informações.

(SAIR DO JOGO / ENTRAR NO JOGO): São os dois botões que você entra no jogo e saí do jogo "Geralmente os 2 starts". Ao apertar um desses dois botões você entra no jogo para jogar, quando estiver dentro do jogo, você aperta os dois botões (por 10 segundos) para sair do jogo.

(Transferir Ficha) São os botões utilizados para transferir as fichas do menu principal para o emulador. Geralmente é apertando um dos dois STARTS....Segure start para transferir a ficha !!Mas lembre-se, se apertar os 2 starts juntos, você sairá do jogo, mas se apertar 1 start por 5 segundos você transferirá a ficha.

(VOLTAR MENU SYSTEM): Quando você ativa o Menu System, ao apertar F8 no teclado. Você poderá voltar para o menu de seleção de emuladores, assim que apertar um desses dois botões, mas caso o menu system estiver desativado, esses dois botões serão usados para ir para o próximo ou anterior emulador.

**Comment by mpanjo** [comment]
valeu obrigado
