### ISSUE TITLE
 CONTATO COMERCIAL - COMPRA E SUPORTE DA MULTIJOGOS

### ISSUE THREAD

**Issue by skurbold** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#20]
Boa tarde Pedro, Segue meu e-mail para contato.
tenho interesse em adquirir o sistema de MultiJogos
fernando.soriedem@gmail.com

**Comment by pedrowarlock** [comment]
Oi, qualquer problema sobre o sistema, mantenha aqui no tópico, atualmente não trabalho com compra ou venda, meu trabalho é manter a atualização do sistema de acordo com as doações direta ao sistema via paypal. Obrigado!
