### ISSUE TITLE
ePSXe não fecha no GameLauncher

### ISSUE THREAD

**Issue by CAOS-GAMER** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#21]
Primeiramente gostaria de agradecer por disponibilizar seu projeto.
Então, estava mexendo no sistema e resolvi trocar o retroarch pelo ePSXe para emular o Playstation 1 (problema de execução pelo retroarch), adição do emulador ok, contagem e afins tudo ok, mas tive o problema de que quando fecho o emulador ele fica rodando em 2° plano, tem alguma forma de fazer com que o GameLauncher envie um Esc para o emulador, ou que feche o mesmo?
O modo Freeplay não adiciona credito automático também nos emuladores por habilidade.
Tem algo que se possa fazer?
Estou usando o mame DirectImput mas não são adicionados creditos apertando diretamente o start.
Agradeço desde já pela atenção.

**Comment by pedrowarlock** [comment]
Não se fecha o sistema pelo ESC, o botão certo de se fechar é o botão definido pelo joystick ou o botão 6 do teclado numerico.
