### ISSUE TITLE
Função "REMOVER_EMULADOR" não funciona

### ISSUE THREAD

**Issue by fabriciocr2** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#28]
Boa tarde amigo,por favor teria como me ajudar com isso?
Quando uso a função remover emulador na multijogos ela não remove e nem adiciona os emuladores... Porém se eu coloco o comando 
Direto no advmenu.ini ela funciona...gostaria de habilitar essa função na multijogos,como fazer? Obrigado

**Comment by pedrowarlock** [comment]
Problema já resolvido
