### ISSUE TITLE
Mame com mensagens de tempo e quantidade de creditos

### ISSUE THREAD

**Issue by fabriciocr2** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#29]
Boa tarde,teria como fazer um tutorial explicando como compilar o mame com as mensagens de tempo pra envio de credito,saída do emulador e quantidade de ficha disponíveis?
Achei interessante essa função adicionada ao emulador...

**Comment by pedrowarlock** [comment]
Existem diversos tutoriais de c++ pela internet e compilação do mame você vê no site oficial: https://www.mamedev.org/index.php
