### ISSUE TITLE
Adicionar novos Temas

### ISSUE THREAD

**Issue by marcospc20** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#3]
Olá Pedro tudo bem! Obrigado por compartilhar seu sistema que é maravilhoso.
minha duvida é sobre tema eu adicionei um novo tema deu tudo certo apareceu na lista de troca de temas editei temas.ini só estou tendo um problema que é editar o arquivo amp. mesmo fazendo qualquer edição no arquivo amp o tema não sofre nenhuma mudança tipo tamanho da janela de snap e ou posição da lista e percebi que mesmo deletando o arquivo amp o tema funciona assim mesmo como si os padrões de tema já estivessem no source.
como faço para editar os novos temas que eu adiciono?

**Comment by pedrowarlock** [comment]
O sistema de troca de tema funciona da seguinte forma. O tema fica na pasta que você criou, quando você clica em selecionar um novo tema utilizando o menu F8 do sistema. O tema é copiado da pasta original e colado na pasta "layout" dessa forma você para alterar o seu tema, terá que ir na pasta de onde você criou ele, alterar ele lá, em seguida ir até o menu F8 do menu e selecionar ele novamente, esse processo irá recopiar o tema para a pasta "Layouts"

https://www.youtube.com/watch?v=CGlR3pXaViY
