### ISSUE TITLE
Problemas com controle jamma

### ISSUE THREAD

**Issue by dalinfoarts** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#30]
Funciona tudo direitinho mas quando instalo o 3º controle do jamma com joytokey ele da erro na hora de entrar no jogo, só aceita com 2 controles instalados, tentei com um outro controle usb e também deu erro, só funciona com 2 controles.

**Comment by Layonwin** [comment]
> Funciona tudo direitinho mas quando instalo o 3º controle do jamma com joytokey ele da erro na hora de entrar no jogo, só aceita com 2 controles instalados, tentei com um outro controle usb e também deu erro, só funciona com 2 controles.

Também percebi isso, quando pluga mais de 3 controles na hora de configurar o controle no advmenu.  E espera sentado que se o autor responder, vai ser até milagre kkkkkkkk. Tenta ver as linhas de código no game launcher. Se vc manjar um pouco de programação. Eu ia até mexer, mas tô sem tempo.

**Comment by pedrowarlock** [comment]
> Funciona tudo direitinho mas quando instalo o 3º controle do jamma com joytokey ele da erro na hora de entrar no jogo, só aceita com 2 controles instalados, tentei com um outro controle usb e também deu erro, só funciona com 2 controles.

Anotado para futuras atualizações.



> > Funciona tudo direitinho mas quando instalo o 3º controle do jamma com joytokey ele da erro na hora de entrar no jogo, só aceita com 2 controles instalados, tentei com um outro controle usb e também deu erro, só funciona com 2 controles.
> 
> Também percebi isso, quando pluga mais de 2 controles na hora de configurar o controle no advmenu. E espera sentado que se o autor responder, vai ser até milagre kkkkkkkk. Tenta ver as linhas de código no game launcher. Se vc manjar um pouco de programação. Eu ia até mexer, mas tô sem tempo.

O desenvolvimento do sistema só funciona na base da doação, se sentir incomodado com o tempo de resposta do desenvolvimento, então faça uma doação para que o projeto andará mais rápido.

**Comment by dalinfoarts** [comment]
O amigo, ajuda nóis ai, veja que mais um teve este problema com controle, vamos negociar esta solução pra que rode perfeito, estarei fazendo uma doação pra ve se te anima Ok abraço!!
