### ISSUE TITLE
Taito modo ficha.

### ISSUE THREAD

**Issue by VITOR1981** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#4]
Pedro parabéns pelo projeto, a pergunta, tem como deixar o contador de fichas aparecendo nos jogos da taito? aqui nos jogos da taito aparece o contador de tempo e quando entro na lista de jogos (ainda não instalei nenhum) a função colocar no modo ficha fica bloqueado.

**Comment by pedrowarlock** [comment]
Para colocar o modo ficha no taito, selecione o jogo lá no menu, aperte F8 com o jogo selecionado, vá até modo FICHA/TEMPO, e selecione modo ficha. (Algumas funções do menu F8, necessita que tenha pelo menos um jogo instalado)

**Comment by VITOR1981** [comment]
Obrigado deu certo aqui, foi só colocar o jogo na pasta.
