### ISSUE TITLE
Adicionar sistemas que não estão na lista

### ISSUE THREAD

**Issue by fabriciocr2** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#5]
Boa tarde amigo, obrigado por disponibilizar a multijogos...
Me diz uma coisa,caso eu queira adicionar sistemas que não estão pre configurados por você tipo uma jukebox é possível? Se for possível ela vai funcionar por ficha ou tempo?

A configuração dos controles pode ser feita em controles USB? E essas configurações eu faço pela configuração de controles no menu de configuração ou teria que ser feita diretamente no joytokey?

Obrigado novamente pelo belo trabalho...

**Comment by pedrowarlock** [comment]
Pode sim adicionar quantos sistemas quiser.

Os controles podem ser modificados sem a necessidade do joytokey

**Comment by fabriciocr2** [comment]
Na parte de controles pensei que fosse possível modificar somente os principais,no menu de configuração não vi parte pra configurar os botões de ação vou olhar mais tarde...

Obrigado pela ajuda...
