### ISSUE TITLE
Verificar possivel Bug troca de temas

### ISSUE THREAD

**Issue by fabriciocr2** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#6]
boa tarde Pedro,hoje estava adicionando jogos ao sistema pra colocar em meu bartop,mas notei que quando vou mudar de um tema pra outro ele fecha a multijogos pra fazer a troca porém não abre novamente.....

PS: to usando a tecla enter pra selecionar o tema desejado...

**Comment by pedrowarlock** [comment]
Você não pode trocar o nome do executável "advmenu.exe"

**Comment by fabriciocr2** [comment]
Não troquei,está do mesmo jeito que baixei....

**Comment by pedrowarlock** [comment]
> Não troquei,está do mesmo jeito que baixei....

Qual tema você selecionou? Pode postar fotos ou algo que mostre o bug em ação?

**Comment by fabriciocr2** [comment]
Então acontece com qualquer tema...quando seleciono o tema ela fecha normalmente sem erro nenhum,porém não abre com o tema novo...sabe me dizer se ela roda bem em sistema 32x? Coloquei em uma máquina mais simples e tô achando que talvez possa ser isso...

**Comment by pedrowarlock** [comment]
> Então acontece com qualquer tema...quando seleciono o tema ela fecha normalmente sem erro nenhum,porém não abre com o tema novo...sabe me dizer se ela roda bem em sistema 32x? Coloquei em uma máquina mais simples e tô achando que talvez possa ser isso...

 Qual sistema operacional você está usando?

**Comment by fabriciocr2** [comment]
Windows 7 32x

**Comment by pedrowarlock** [comment]
> Windows 7 32x

O que eu recomendo é baixar novamente o sistema e verificar se está funcionando, acredito que você tenha alterado algo que está impedindo isso.

**Comment by fabriciocr2** [comment]
Vou baixar,só se corrompeu algo durante o download...acabei de baixar extrai e fiz o teste logo de cara aconteceu isso...mas pensei que fosse por não ter emuladores nem as roms...adicionei e mesmo assim permaneceu o problema...vou baixar de novo pra testar e amanhã do retorno... Obrigado pela ajuda...

**Comment by fabriciocr2** [comment]
Problema resolvido amigo,formatei o PC e agora deu certo... obrigado pela atenção
