### ISSUE TITLE
adicionar sega model

### ISSUE THREAD

**Issue by mpanjo** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#7]
Bom pode me dar uma dica de como fazer pro sega model abrir o jogo?
Adicinei o emulador mas ele nao carrega o jogo abre somente a tela do emulador

**Comment by pedrowarlock** [comment]
Eu precisaria saber como você executou ele no sistema.

**Comment by mpanjo** [comment]
Bom dia,  estou usando o proprio emulador do model2. Troquei no rc o nome do retroarch e coloquei o do.model2. Quando eu dou um enter em cima do jogo ele carrega a tela do emulador e não abre o jogo. Obrigado pelo retorno.

**Comment by pedrowarlock** [comment]
você precisa ir no arquivo .ini referente ao emulador que você está editando na pasta "ini" e mudar a linha "Retroarch = 1" para "Retroarch = 0"

**Comment by mpanjo** [comment]
Então eu ja tinha feito isso mas com relação ao emulador do sega model não deu certo. Ele abre somente a janela do emulador mas não carrega o jogo.

**Comment by pedrowarlock** [comment]
> Então eu ja tinha feito isso mas com relação ao emulador do sega model não deu certo. Ele abre somente a janela do emulador mas não carrega o jogo.

Se tiver um link do emulador com um jogo, eu posso testar aqui.

**Comment by mpanjo** [comment]
Blz amanhã eu mando o link com uma rom. Valeu

**Comment by CaioDeneditoDrumond** [comment]
Ola boa noite.
Vc poderia se possivel me ajudar com as linha de comandos para eu add emuladores nesse seu sistema multijogos ,pq eu querendo os emuladores individual ao inves de retroarch. Como num antigo sistema q vc tinha estou querendo os emuladores desse seu sistema antigo que tinha pastacom o comandodo(LauncherBox,LauncherBox) e colocar nesse atual e colocar mais outros emuladores.
