### ISSUE TITLE
Retroarch para mostrar contador de tempo

### ISSUE THREAD

**Issue by tommoreira** [pedrowarlock/advmenuPlus-PedroWarlock-comercial-system#8]
Olá Pedro, primeiramente quero lhe agradecer por ter compartilhado esse sistema que será de muito valor para meu projeto de máquina de fliperama que pretendo colocar na garagem da minha casa.
Já procurei informações e tentei configurar várias vezes o Retroarch para aparecer o contador de tempo, mas não tive sucesso.
Gostaria de ver com você a possibilidade de me enviar a pasta com o retroarch já configurado para poder aparecer sobreposto o contador na tela.
Vou contribuir com o seu projeto amanhã já vou fazer uma doação e mais uma vez muito obrigado!
Qualquer coisa se puder mandar o retroarch o meu email é tommoreira10@gmail.com

**Comment by pedrowarlock** [comment]
No momento eu não posso enviar o retroarch, a versão 32bits pesa 300mb e a versão 64bits pesa 1gb. E minha internet é de 10mb. Para libera-lo, eu precisaria de uns 3 dias para upar.
